platformName: Android
platformVersion: 8.1.0
deviceName: XXX
udid: ZX1G429WZM
#udid: 9a7caf5c
noReset: False

appPackage: com.tal.kaoyan
appActivity: com.tal.kaoyan.ui.activity.SplashActivity

unicodeKeyboard: True
resetKeyboard: True
automationName: UiAutomator2
ip: 127.0.0.1
port: 4723